//
//  PrivacyView.swift
//  Homework assistant
//
//  Created by Hector Wu on 3/3/2026.
//


// Filename: PrivacyView.swift
// 用途：展示隐私政策与免责声明

import SwiftUI

struct PrivacyView: View {
    @Binding var isPresented: Bool
    var language: AppLanguage
    
    var isEnglish: Bool { language == .english }
    
    var body: some View {
        VStack(spacing: 0) {
            // 标题栏
            HStack {
                Text(isEnglish ? "Privacy Policy & User Agreement" : "隐私政策与用户协议")
                    .font(.headline)
                Spacer()
                Button(action: { isPresented = false }) {
                    Image(systemName: "xmark.circle.fill")
                        .foregroundStyle(.gray)
                        .font(.title2)
                }
                .buttonStyle(.plain)
            }
            .padding()
            .background(Color(nsColor: .controlBackgroundColor))
            
            Divider()
            
            // 内容区
            ScrollView {
                VStack(alignment: .leading, spacing: 15) {
                    Group {
                        Text(isEnglish ? "1. Data Storage" : "1. 数据存储")
                            .font(.headline)
                        Text(isEnglish ? 
                             "All homework data generated by Homework Assistant is stored LOCALLY on your device using Apple's SwiftData technology. We do not upload your schedule to any cloud servers controlled by the developer." :
                             "本软件（Homework Assistant）生成的所有作业数据均通过 Apple SwiftData 技术存储在您的**本地设备**上。开发者不会将您的日程数据上传至任何服务器。")
                        
                        Text(isEnglish ? "2. Third-Party API Service (Groq)" : "2. 第三方 API 服务 (Groq)")
                            .font(.headline)
                        Text(isEnglish ?
                             "This app requires an API Key from Groq to function. Groq is a third-party service provider. When you use the AI parsing feature, your text input is sent to Groq's servers for processing. Please refer to Groq's privacy policy for how they handle data. The developer of this app is not responsible for Groq's service availability or data handling." :
                             "本软件需要使用 Groq 提供的 API Key 才能运行 AI 解析功能。Groq 是独立的第三方服务提供商。\n\n当您点击发送时，您的输入文本将被发送至 Groq 的服务器进行处理。请参阅 Groq 的隐私政策以了解其数据处理方式。\n\n**免责声明**：本软件开发者与 Groq 无关联，不对第三方服务的可用性、准确性或数据安全承担责任。")
                        
                        Text(isEnglish ? "3. User Responsibility" : "3. 用户责任")
                            .font(.headline)
                        Text(isEnglish ?
                             "Users are responsible for the content they input. Do not input sensitive personal information (such as passwords, financial data) into the AI input field." :
                             "用户需对自己输入的内容负责。请勿在 AI 输入框中输入敏感个人信息（如密码、银行账号、身份证号等）。")
                        
                        Text(isEnglish ? "4. Updates & Changes" : "4. 协议更新")
                            .font(.headline)
                        Text(isEnglish ?
                             "Using this software implies agreement to these terms." :
                             "使用本软件即视为您同意上述条款。本声明可能随软件版本更新而调整。")
                    }
                    .font(.body)
                    .foregroundStyle(.primary)
                }
                .padding()
            }
        }
        .frame(width: 500, height: 600)
    }
}